name: chip8
version: "1.0.3"
summary: CHIP-8 Emulator
description: |
  A simple CHIP-8 emulator in C and SDL2.

base: core22
confinement: devmode

parts:
  chip8:
    plugin: autotools
    source: https://github.com/amhue/chip8.git
    build-packages:
      - gcc
      - make
      - libsdl2-dev

apps:
  chip8:
    command: chip8
    desktop: true
    desktop-file: chip8.desktop
